### ISSUE TITLE
Big flickering when driving LEDs in realtime using USB Serial...

### ISSUE THREAD

**Issue by sblantipodi** [Makuna/NeoPixelBus#525]
**Describe the bug**
Driving LEDs via USB Serial creates big flickering when WiFi is active even at 460800 baudrate.
There is big flickering even when there is no WiFi at 1 million baudrate.

**To Reproduce**
Try to run LEDs in real time at 60FPS or even 30FPS when WiFi is active.
Big flickering happens.
Flickering is reduced when WiFi is off, but there still there if driving LEDs at 1 million baudrate.

This does not happen on ESP8266.

**Expected behavior**
No flickering excpected

**Development environment (please complete the following information):**
 - OS: Win10
 - Build Environment PlatformIO 5.2.1
 - Board target ESP32
 - Library version [e.g. v2.3.4] - latest 2.6.9

**Additional context**
I have tried using different RTOS tasks as described here:  
https://github.com/Makuna/NeoPixelBus/wiki/ESP32-and-RTOS-Tasks  
but it does not help.   
Using NeoEsp32I2s1800KbpsMethod

**Comment by Makuna** [comment]
Since you are updating constantly, that flicker is caused an errant communications issue and not something systemic.  Usually the timing is off (you have different chips than WS2812).  You are using ESP32 and not ESP32C2 or ESP32S3? 

Try `NeoEsp32I2s1Ws2812xMethod` instead of `NeoEsp32I2s1800KbpsMethod`.  Neo800KbpsMethod maps to this but you are not using it for the ESP32, the original WS2812 had a short reset time, the latest have a much longer reset time; and you maybe hitting this since you are sending so quickly one after another.  The method naming convention is that if you use the i2s name specifically, then then chip name must be specific (2812x, not 2812).  But the none specific name (Neo800KbpsMethod) uses the most "compatible".

**Comment by Makuna** [comment]
Are you using level shifters at all?
RMT is more sensitive to interrupt saturation than I2s.  But I2s can be effected by it. I suspect this is what you are running into. There is little I can do.  This requires the sketch writer to reduce ISR usage (less ISRs).  

With I2s, the ISR is called once per Show() and the actual data sending is done by i2s DMA hardware.  

Something you can try, but I have no idea if it will help.

Switch back to I2s method.
On this line of NeoPixelBus https://github.com/Makuna/NeoPixelBus/blob/a561a8294eb1ba1eaeeafc91467b9ab828dfcfa8/src/internal/Esp32_i2s.c#L387

Try increasing the priority by using ESP_INTR_FLAG_LEVEL2 and see if it helps.  Keep increasing upto ESP_INTR_FLAG_LEVEL6, but in general this isn't the best approach.

**Comment by Makuna** [comment]
In general, its never a good idea to increase the priority, but I thought it would be worth trying.

I am thinking the Serial ISR is the culprit here; in that it either takes too long in its ISR or its ISR is triggering far too often.

Also, which cores are you running your work on?  The ESP32 has two cores, leave NeoPixelBus work on the first core, try to move WiFi and Serial onto the second core (see ESP32 tasks and core affinity APIs).

**Comment by Makuna** [comment]
Try the latest Github version with RMT again and make sure to get the updated board support.  There is a fix for latest IDF with interrupt level.

**Comment by sblantipodi** [comment]
@Makuna thanks for the continued help and for the great work here, I love your lib.
unfortunantly the flicker is still there as before.

Using the latest master branch from github and the latest Arduino framework for ESP32.

**Comment by Makuna** [comment]
@sblantipodi Some changes have been made to the i2s method lately.  Have you tried the latest?

**Comment by sblantipodi** [comment]
@Makuna I'm always glad to upgrade to the latest version of your great lib.
I'll test it and report back soon. thanks!

**Comment by sblantipodi** [comment]
@Makuna I'm driving 100 LEDs at 120FPS at 1.5 million baudrate on an ESP32 that uses CP2104 UART chip via USB,
during the "color stream via USB" there is a process that uses MQTT to send framerate data to the broker along with other informations.
I have done another test with "UDP stream (no USB)" with 500 LEDs at 60FPS and there is no regression.

No flickering at all in every conditions, I'm closing the issue since the problem is completely fixed.

Thank you for your awesome work here Makuna, this lib is simply amazing.

Best wishes
Davide
