### ISSUE TITLE
Issue turning off pixels prior to sleep.

### ISSUE THREAD

**Issue by jumper-d-1981** [Makuna/NeoPixelBus#655]
I did not realize that questions may get deleted.  That is fine, still gonna ask.

Hey!  Am I permitted to ask questions concerning neopixelbus on here?

I have an issue where I cannot turn off my pixels before deep_sleep on esp32 and esp32 home chat said to ask here, home assistant people suggested using a software switch but that does not seem to work.  I need some advice.

Essentially, when I deep_sleep my device, the lights stay on.  How would I disable lights prior to sleep?  I tried assigning a software switch to the same GPIO but that did not work.  Someone suggested using another pin and jumping a resistor to the data pin.

Thoughts?  Thanks.

**Comment by Makuna** [comment]
You found the discussions, deleting. ;-)

I am curious as to your experience that you didn't notice the references to Discussions?  You did see them?  I get this a lot and I have been asking GitHub for a solution to promote Discussions for Q/A rather than Issues and having your experience documented might shed some light on a better approach/solution.

**Comment by jumper-d-1981** [comment]
Well, to be honest, very few people have active discussions on their github pages...at least of the ones I have viewed.  So my 1st reaction is to use the "Issues" as the forum.  Seems to typically work.  BUT...now I know.  lol.
